version: '3.8'

services:
  db:
    container_name: network_db
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - network_api

  pgadmin:
    container_name: network_pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - network_api

  web:
    container_name: network_web
    build: .
    privileged: true
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=django_app.settings
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DEBUG=1
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      db:
        condition: service_started
    command: /start.sh
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      - network_api

networks:
  network_api:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
