# Generated by Django 4.2.7 on 2024-11-10 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NetworkTopology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("hosts", models.JSONField()),
                ("switches", models.JSONField()),
                ("links", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PacketTrace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_node", models.CharField(max_length=200)),
                ("destination_node", models.CharField(max_length=200)),
                ("packet_config", models.JSONField()),
                ("route", models.JSONField(default=list)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("sending", "Sending"),
                            ("received", "Received"),
                            ("dropped", "Dropped"),
                            ("completed", "Completed"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("current_node", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "topology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packet_traces",
                        to="django_app.networktopology",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NetworkNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "node_type",
                    models.CharField(
                        choices=[("host", "Host"), ("switch", "Switch")], max_length=10
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="django_app.networktopology",
                    ),
                ),
            ],
            options={
                "unique_together": {("topology", "name")},
            },
        ),
    ]
