# Generated by Django 4.2.7 on 2025-05-05 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_app", "0004_networktopology_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentgroup",
            name="created_by",
        ),
        migrations.AddField(
            model_name="educationalmaterial",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="educationalmaterial",
            name="material_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("video", "Video"),
                    ("quiz", "Quiz"),
                    ("assignment", "Assignment"),
                    ("simulation", "Simulation"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="studentgroup",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="student_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="studentgroup",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="educationalmaterial",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="studentgroup",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentgroup",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
