# Generated by Django 4.2.7 on 2025-05-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_app", "0005_remove_studentgroup_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="networktopology",
            name="routers",
            field=models.JSONField(default=list),
        ),
    ]
